### ISSUE TITLE
Sebastian should be room 8

### ISSUE THREAD

**Issue by jeffozozo** [se3150/f24-group-adventure-we-reallonthesameteam#32]
Sebastian - your room number is 8. Kyleigh's is 9.

go take a look at student_map.txt.  Your room looks like this:

Room:8 - Sebastian Hernandez
 north,7
 west,9

You probably don't need to change much, just the name.

**Comment by sebastianh034** [comment]
just fixed the issue renamed my room to the correct one "room8_sebastian"
