### ISSUE TITLE
Review of Room 24 

### ISSUE THREAD

**Issue by aolanioaks** [se3150/f24-group-adventure-we-reallonthesameteam#6]
What items are done particularly well in the code:
I’ve reviewed your code and it looks overall greatly structured. You’ve created your room into a Crystal room which is a nice touch. Everything is written out nicely and the room descriptions are great as well as the functionality of the room. 

What suggestions would you make to improve the code? The one thing I suggest you add would be to test your code, I didn’t see any test suites. But overall everything looks great. 

How well is the code organized: Great

Consistent and clear variable names: Great
How well did the code meet the requirements: I believe everything was met so great!
How testable is the code: Great

**Comment by juliassilvestrin** [comment]
Thank you!!
