### ISSUE TITLE
Review of room 15

### ISSUE THREAD

**Issue by juliassilvestrin** [se3150/f24-group-adventure-we-reallonthesameteam#7]
What items are done particularly well in the code:
I've reviewed your code and it's really well done. I like how you made the well glow in the first room. Everything works well and the rooms are fun to read about. All the room descriptions are nicely written and the game mechanics work well.

What suggestions would you make to improve the code:
There's just one small typo in the spider room's description print where it prints "self.description" as text instead of showing the actual description. 

How well is the code organized: Great

Consistent and clear variable names: Great

How well did the code meet the requirements: Great

How testable is the code: Great

**Comment by aolanioaks** [comment]
Thank you for reviewing it!
